export const STATE_DATA = {
  "Alabama": { capital: "Montgomery", population: "5 Million", area: "52,420 sq mi", fact: "The first rocket to put humans on the moon was built here!" },
  "Alaska": { capital: "Juneau", population: "730,000", area: "663,268 sq mi", fact: "It's the largest state and has over 3 million lakes!" },
  "Arizona": { capital: "Phoenix", population: "7.1 Million", area: "113,990 sq mi", fact: "Home to the massive and beautiful Grand Canyon!" },
  "Arkansas": { capital: "Little Rock", population: "3 Million", area: "53,179 sq mi", fact: "The only US state where you can mine your own diamonds!" },
  "California": { capital: "Sacramento", population: "39 Million", area: "163,696 sq mi", fact: "Has both the highest and lowest points in the contiguous US!" },
  "Colorado": { capital: "Denver", population: "5.8 Million", area: "104,094 sq mi", fact: "Has the highest paved road in North America!" },
  "Connecticut": { capital: "Hartford", population: "3.6 Million", area: "5,543 sq mi", fact: "The hamburger was invented here in 1900!" },
  "Delaware": { capital: "Dover", population: "1 Million", area: "1,949 sq mi", fact: "The very first state to ratify the US Constitution!" },
  "Florida": { capital: "Tallahassee", population: "21.5 Million", area: "65,758 sq mi", fact: "No matter where you are, you're never more than 60 miles from the ocean!" },
  "Georgia": { capital: "Atlanta", population: "10.7 Million", area: "59,425 sq mi", fact: "Known as the Peach State, but they actually produce more peanuts!" },
  "Hawaii": { capital: "Honolulu", population: "1.4 Million", area: "10,931 sq mi", fact: "The only state made entirely of islands!" },
  "Idaho": { capital: "Boise", population: "1.8 Million", area: "83,569 sq mi", fact: "Known for potatoes, but also called the Gem State for its rare minerals!" },
  "Illinois": { capital: "Springfield", population: "12.8 Million", area: "57,914 sq mi", fact: "The world's first skyscraper was built in Chicago!" },
  "Indiana": { capital: "Indianapolis", population: "6.7 Million", area: "36,420 sq mi", fact: "Home to the famous Indy 500 car race!" },
  "Iowa": { capital: "Des Moines", population: "3.1 Million", area: "56,273 sq mi", fact: "Has more pigs than humans! Oink! 🐷" },
  "Kansas": { capital: "Topeka", population: "2.9 Million", area: "82,278 sq mi", fact: "Produces enough wheat to bake 36 billion loaves of bread!" },
  "Kentucky": { capital: "Frankfort", population: "4.5 Million", area: "40,408 sq mi", fact: "Has the longest known cave system in the world, Mammoth Cave!" },
  "Louisiana": { capital: "Baton Rouge", population: "4.6 Million", area: "52,378 sq mi", fact: "The birthplace of Jazz music! 🎷" },
  "Maine": { capital: "Augusta", population: "1.3 Million", area: "35,385 sq mi", fact: "Produces 99% of the blueberries in the United States!" },
  "Maryland": { capital: "Annapolis", population: "6 Million", area: "12,406 sq mi", fact: "The US National Anthem was written here!" },
  "Massachusetts": { capital: "Boston", population: "7 Million", area: "10,554 sq mi", fact: "The chocolate chip cookie was invented here! 🍪" },
  "Michigan": { capital: "Lansing", population: "10 Million", area: "96,716 sq mi", fact: "Has the longest freshwater shoreline in the world!" },
  "Minnesota": { capital: "St. Paul", population: "5.7 Million", area: "86,936 sq mi", fact: "Known as the Land of 10,000 Lakes (actually has over 11,000)!" },
  "Mississippi": { capital: "Jackson", population: "2.9 Million", area: "48,432 sq mi", fact: "The birthplace of the Teddy Bear! 🧸" },
  "Missouri": { capital: "Jefferson City", population: "6.1 Million", area: "69,704 sq mi", fact: "The Gateway Arch in St. Louis is the tallest man-made monument in the US!" },
  "Montana": { capital: "Helena", population: "1 Million", area: "147,040 sq mi", fact: "Has the largest migratory elk herd in the nation!" },
  "Nebraska": { capital: "Lincoln", population: "1.9 Million", area: "77,348 sq mi", fact: "Kool-Aid was invented here in 1927!" },
  "Nevada": { capital: "Carson City", population: "3.1 Million", area: "110,572 sq mi", fact: "The driest state in the US!" },
  "New Hampshire": { capital: "Concord", population: "1.3 Million", area: "9,349 sq mi", fact: "The first state to have its own state constitution!" },
  "New Jersey": { capital: "Trenton", population: "9.2 Million", area: "8,723 sq mi", fact: "Has the most diners in the world and is called the Diner Capital!" },
  "New Mexico": { capital: "Santa Fe", population: "2.1 Million", area: "121,590 sq mi", fact: "Home to the annual Albuquerque International Balloon Fiesta!" },
  "New York": { capital: "Albany", population: "20.2 Million", area: "54,555 sq mi", fact: "The Statue of Liberty was a gift from France to the US in 1886!" },
  "North Carolina": { capital: "Raleigh", population: "10.4 Million", area: "53,819 sq mi", fact: "The Wright brothers flew the first successful airplane here!" },
  "North Dakota": { capital: "Bismarck", population: "779,000", area: "70,698 sq mi", fact: "Grows more sunflowers than any other state! 🌻" },
  "Ohio": { capital: "Columbus", population: "11.7 Million", area: "44,826 sq mi", fact: "Seven US Presidents were born here!" },
  "Oklahoma": { capital: "Oklahoma City", population: "3.9 Million", area: "69,899 sq mi", fact: "Has the largest population of Native American descent!" },
  "Oregon": { capital: "Salem", population: "4.2 Million", area: "98,379 sq mi", fact: "Has the deepest lake in the US, Crater Lake!" },
  "Pennsylvania": { capital: "Harrisburg", population: "13 Million", area: "46,054 sq mi", fact: "The Declaration of Independence was signed here in Philadelphia!" },
  "Rhode Island": { capital: "Providence", population: "1 Million", area: "1,214 sq mi", fact: "The smallest state in the US, but has 400 miles of coastline!" },
  "South Carolina": { capital: "Columbia", population: "5.1 Million", area: "32,020 sq mi", fact: "The first shots of the American Civil War were fired here!" },
  "South Dakota": { capital: "Pierre", population: "886,000", area: "77,116 sq mi", fact: "Home to Mount Rushmore, featuring four giant presidents' faces!" },
  "Tennessee": { capital: "Nashville", population: "6.9 Million", area: "42,144 sq mi", fact: "The Great Smoky Mountains is the most visited national park!" },
  "Texas": { capital: "Austin", population: "29 Million", area: "268,596 sq mi", fact: "The only state to have the flags of 6 different nations fly over it!" },
  "Utah": { capital: "Salt Lake City", population: "3.2 Million", area: "84,897 sq mi", fact: "Has five incredible National Parks, known as the Mighty 5!" },
  "Vermont": { capital: "Montpelier", population: "643,000", area: "9,616 sq mi", fact: "Produces the most maple syrup in the United States! 🍁" },
  "Virginia": { capital: "Richmond", population: "8.5 Million", area: "42,775 sq mi", fact: "The first permanent English settlement was established here in Jamestown!" },
  "Washington": { capital: "Olympia", population: "7.7 Million", area: "71,298 sq mi", fact: "The only state named after a US President!" },
  "West Virginia": { capital: "Charleston", population: "1.7 Million", area: "24,230 sq mi", fact: "The first state to have a sales tax!" },
  "Wisconsin": { capital: "Madison", population: "5.8 Million", area: "65,496 sq mi", fact: "Produces more cheese than any other state! 🧀" },
  "Wyoming": { capital: "Cheyenne", population: "578,000", area: "97,813 sq mi", fact: "The state with the lowest population, but home to Yellowstone National Park!" }
};
