export const STATE_FACTS = {
  "Alabama": "The first rocket to put humans on the moon was built here!",
  "Alaska": "It's the largest state and has over 3 million lakes!",
  "Arizona": "Home to the massive and beautiful Grand Canyon!",
  "Arkansas": "The only US state where you can mine your own diamonds!",
  "California": "Has both the highest and lowest points in the contiguous US!",
  "Colorado": "Has the highest paved road in North America!",
  "Connecticut": "The hamburger was invented here in 1900!",
  "Delaware": "The very first state to ratify the US Constitution!",
  "Florida": "No matter where you are, you're never more than 60 miles from the ocean!",
  "Georgia": "Known as the Peach State, but they actually produce more peanuts!",
  "Hawaii": "The only state made entirely of islands!",
  "Idaho": "Known for potatoes, but also called the Gem State for its rare minerals!",
  "Illinois": "The world's first skyscraper was built in Chicago!",
  "Indiana": "Home to the famous Indy 500 car race!",
  "Iowa": "Has more pigs than humans! Oink! 🐷",
  "Kansas": "Produces enough wheat to bake 36 billion loaves of bread!",
  "Kentucky": "Has the longest known cave system in the world, Mammoth Cave!",
  "Louisiana": "The birthplace of Jazz music! 🎷",
  "Maine": "Produces 99% of the blueberries in the United States!",
  "Maryland": "The US National Anthem was written here!",
  "Massachusetts": "The chocolate chip cookie was invented here! 🍪",
  "Michigan": "Has the longest freshwater shoreline in the world!",
  "Minnesota": "Known as the Land of 10,000 Lakes (actually has over 11,000)!",
  "Mississippi": "The birthplace of the Teddy Bear! 🧸",
  "Missouri": "The Gateway Arch in St. Louis is the tallest man-made monument in the US!",
  "Montana": "Has the largest migratory elk herd in the nation!",
  "Nebraska": "Kool-Aid was invented here in 1927!",
  "Nevada": "The driest state in the US!",
  "New Hampshire": "The first state to have its own state constitution!",
  "New Jersey": "Has the most diners in the world and is called the Diner Capital!",
  "New Mexico": "Home to the annual Albuquerque International Balloon Fiesta!",
  "New York": "The Statue of Liberty was a gift from France to the US in 1886!",
  "North Carolina": "The Wright brothers flew the first successful airplane here!",
  "North Dakota": "Grows more sunflowers than any other state! 🌻",
  "Ohio": "Seven US Presidents were born here!",
  "Oklahoma": "Has the largest population of Native American descent!",
  "Oregon": "Has the deepest lake in the US, Crater Lake!",
  "Pennsylvania": "The Declaration of Independence was signed here in Philadelphia!",
  "Rhode Island": "The smallest state in the US, but has 400 miles of coastline!",
  "South Carolina": "The first shots of the American Civil War were fired here!",
  "South Dakota": "Home to Mount Rushmore, featuring four giant presidents' faces!",
  "Tennessee": "The Great Smoky Mountains is the most visited national park!",
  "Texas": "The only state to have the flags of 6 different nations fly over it!",
  "Utah": "Has five incredible National Parks, known as the Mighty 5!",
  "Vermont": "Produces the most maple syrup in the United States! 🍁",
  "Virginia": "The first permanent English settlement was established here in Jamestown!",
  "Washington": "The only state named after a US President!",
  "West Virginia": "The first state to have a sales tax!",
  "Wisconsin": "Produces more cheese than any other state! 🧀",
  "Wyoming": "The state with the lowest population, but home to Yellowstone National Park!"
};
